function asideUI (){
	return '<aside>'
	+'	<div class="row">'
	+'	<div class="col-sm-4 col-md-3 sidebar">'
	+'<div class="mini-submenu">'
	+'    <span class="icon-bar"></span>'
	+'    <span class="icon-bar"></span>'
	+'    <span class="icon-bar"></span>'
	+'</div>'
	+'<div class="list-group" min-width="400px">'
	+'    <span href="#" class="list-group-item active">'
	+'        Payment'
	+'        <span class="pull-right" id="slide-submenu">'
	+'            <i class="glyphicon glyphicon-remove"></i>'
	+'        </span>'
	+'    </span>'
	+'    <a href="#" id="cart_btn" class="list-group-item">'
	+'        <i class="glyphicon glyphicon-shopping-cart"></i> 장바구니'
	+'    </a>'
	+'    <a href="#" id="payHis_btn" class="list-group-item">'
	+'        <i class="glyphicon glyphicon-credit-card"></i> 구매함'
	+'    </a>'
	+'    <a href="#" id="gift_btn"class="list-group-item">'
	+'      <i class="glyphicon glyphicon-gift"></i> 선물함 <span class="badge">14</span>'
	+'    </a>'
	+'  <span href="#" class="list-group-item active">'
	+'        My taste'
	+'        </span>'
	+'    </span>'
	+'    <a href="#" id="analysis_btn" class="list-group-item">'
	+'         <i class="fa fa-user"></i> 취향분석 '
	+'    </a>'
	+'    <a href="#" id="collect_btn" class="list-group-item">'
	+'        <i class="glyphicon glyphicon-heart"></i>  콜렉션'
	+'    </a>'
	+'</div>        '
	+'</div>'
	+'</div>'
	+'</aside> ';}